version: '3.8'

services:
    traefik:
        container_name: traefik
        image: 'traefik:latest'
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './traefik_dynamic.toml:/traefik_dynamic.toml'
            - "./letsencrypt:/letsencrypt"
        ports:
            - '80:80'
            - '443:443'
            - '123:123/udp'
            - '1194:1194/udp'
        networks:
            - web
        command:
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--log.level=ERROR"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=web"
            - "--providers.file.filename=traefik_dynamic.toml"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.openvpn-schule.address=:123/udp"
            - "--entrypoints.openvpn.address=:1194/udp"
            #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
            - "--certificatesresolvers.letsencrypt.acme.email=$email"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
networks:
  web:
    external: true
